Repository wecode-bootcamp-korea/24-2nd-Overdos-backend, pull requests merged in 2021-09, with the labels that each got.

#1 [고영수, 최현수] App 생성 및 모델링
  core/__init__.py
  core/admin.py
  core/apps.py
  core/migrations/__init__.py
  core/models.py
  core/tests.py
  core/views.py
  filling/settings.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  surveys/__init__.py
  surveys/admin.py
  surveys/apps.py
  surveys/migrations/__init__.py
  surveys/models.py
  surveys/tests.py
  surveys/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [최현수] Add : product-list-view
  core/models.py
  debugger.py
  filling/urls.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  products/migrations/0001_initial.py
  products/models.py
  products/tests.py
  products/urls.py
  products/views.py
  surveys/migrations/0001_initial.py
  surveys/models.py
  surveys/urls.py
  surveys/views.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#4 [최현수] food_url - modeling 추가
  products/migrations/0002_food_url.py
  products/models.py
  users/models.py
Labels: Status: Rebase 요청

#3 [filling] 회원가입, 로그인, 카카오로그인 views 작성
  filling/settings.py
  filling/urls.py
  orders/migrations/0001_initial.py
  orders/migrations/__init__.py
  products/migrations/0001_initial.py
  products/migrations/__init__.py
  requirements.txt
  surveys/migrations/__init__.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
  users/tests.py
  users/urls.py
  users/utils.py
  users/views.py
Labels: Status: 리뷰 요청

#5 [최현수,고영수] add : modeling+
  products/models.py
  surveys/models.py
Labels: Status: Rebase 요청

#7 [최현수]설문 조사
  filling/settings.py
  filling/urls.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  orders/migrations/__init__.py
  products/migrations/0001_initial.py
  products/migrations/0002_food_url.py
  products/migrations/__init__.py
  products/models.py
  products/views.py
  surveys/migrations/0001_initial.py
  surveys/migrations/__init__.py
  surveys/urls.py
  surveys/views.py
  users/migrations/0001_initial.py
  users/migrations/__init__.py
Labels: Status: 리뷰 요청

#9 [최현수] survey view - user page suvery result list 작성
  products/tests.py
  surveys/urls.py
  surveys/views.py
Labels: Status: 리뷰 요청

#10 stashed from feature/owen-cart, moved all codes
  orders/tests.py
  orders/views.py
  surveys/migrations/0002_auto_20210930_1426.py
  users/tests.py
  users/utils.py
Labels: Status: 리뷰 요청
